### ISSUE TITLE
Misleading koan about chars

### ISSUE THREAD

**Issue by adolincauthon** [matyb/java-koans#101]
I am going through the koans, which are awesome, and noticed a bit of a misnamed koan. The koan "charsCanOnlyBePositive" is misleading as a char can have a value of 0. Renaming this to "charsCanOnlyBeNonNegative" would be more accurate. 

Super minor nitpick for this awesome program. Thank you for making this.

**Comment by matyb** [comment]
Thanks for the kind words and helping make this project better. It's a valid point. Got [something merged](https://github.com/matyb/java-koans/pull/102) that I think resolves this.
