### ISSUE TITLE
Koan are not re-evaluated when file is edited using emacs

### ISSUE THREAD

**Issue by doug-wade** [matyb/java-koans#33]
I'm using the koans on Ubuntu 12.04 and started out using emacs, but the Koan evaluation loop doesn't work properly while using emacs (nano, vim, and gedit all seem to work as expected, so this isn't a show-stopper or anything).  The Koans are evaluated properly initially, but after the file is edited and saved, an error is emitted and the Koans are not re-evaluated. 

Here's the full output:
Ponder what's going wrong in the: AboutPrimitives class's wholeNumbersAreOfTypeInt method.

Line 12 may offer a clue as to how you may progress, now make haste!
What went wrong: 
expected:<int> but was:<REPLACE ME>

Level: Novice
Progress [XXXX----------------------------------------------] 16/193
Passing Suites: AboutKoans, AboutAssertions, AboutEquality
Remaining Suites: AboutPrimitives, AboutStrings, AboutObjects, AboutLoops, AboutInheritance, AboutCasting, AboutConditionals, AboutConstructors, AboutEnums, AboutExceptions, AboutMethodPreference, AboutOperators, AboutArrays, AboutAutoboxing, AboutCollections, AboutComparison, AboutDates, AboutEquality, AboutFileIO, AboutInnerClasses, AboutLocale, AboutRegularExpressions, AboutSerialization, AboutMocks

Edit & save a koan to reload or enter 'Q' to exit
# User edits AboutPrimitives.java and saves it at this point
Exception in thread "Thread-2" java.lang.RuntimeException: java.io.IOException: File or directory does not exist: /home/local/ANT/dougwade/java-koans-master/koans/src/beginner/.#AboutPrimitives.java
    at com.sandwich.util.io.FileMonitor.notifyListeners(FileMonitor.java:61)
    at com.sandwich.util.io.FileMonitorFactory$2.run(FileMonitorFactory.java:34)
    at java.lang.Thread.run(Thread.java:701)
Caused by: java.io.IOException: File or directory does not exist: /home/local/ANT/dougwade/java-koans-master/koans/src/beginner/.#AboutPrimitives.java
    at com.sandwich.util.io.FileUtils.forEachFile(FileUtils.java:57)
    at com.sandwich.util.io.FileUtils.forEachFile(FileUtils.java:53)
    at com.sandwich.util.io.FileUtils.forEachFile(FileUtils.java:53)
    at com.sandwich.util.io.FileUtils.forEachFile(FileUtils.java:53)
    at com.sandwich.util.io.FileMonitor.getFilesystemHashes(FileMonitor.java:67)
    at com.sandwich.util.io.FileMonitor.notifyListeners(FileMonitor.java:47)
    ... 2 more

**Comment by yubrshen** [comment]
I got the same error when editing with emacs. Once I edit the file even before saving the edits. I would see the error, and when I actually saved my answer, the ./run.sh would not progress further. I'm running the latest master cloned on Feb. 9, 2019 with Ubuntu 18.04 and emacs 26.1. 

I also tried to set 
ignore_from_monitoring=#.*\\.java
in ./koans/app/config.properties following your fix issue #72 
but it didn't work.

**Comment by matyb** [comment]
Ya think the problems [here](https://github.com/matyb/java-koans/commit/3cbe8fcdf585096030de3cd6eff3b24838327925#diff-f47863de913997a15c13028e3357cb79R39) what I'm doing is pretty dumb - just checking if file ends with the string. Wish I'd just made it a regex.

**Comment by yubrshen** [comment]
Are you suggesting that if the following code can be more sophisticated with regular expression matching?
while(file != null){
			String end = file.getAbsolutePath().substring(file.getAbsolutePath().lastIndexOf(System.getProperty("file.separator")) + 1);
			for(String pathToIgnore: ignoredPaths){
				ignore = end.matches(pathToIgnore);
				if(ignore){
					return true;
				}
			}
			file = file.getParentFile();
		}
		return ignore;

I'll give it a try, as it's really painful for me.

**Comment by yubrshen** [comment]
But I need help on how to rebuild the software written in Java. I have been using dynamic language far too long.

**Comment by yubrshen** [comment]
Actually, for my case, I don't need such an eager evaluation before my edits are saved. Would it be simpler to implement?

**Comment by matyb** [comment]
I haven't been in front of a PC, but I'd expirement with:
Flipping the comparison from `end.matches(patternToMatch)` to `patternToMatch.matches(end)` and different regexes in that config file. The docker build can verify the change held and Gradle has tasks to build and copy the artifacts. That's if you're in a hurry, if not I can sort thru this when my kids are :sleeping:
