### ISSUE TITLE
Add Koan for Java 8 Features 

### ISSUE THREAD

**Issue by mavrukin** [matyb/java-koans#41]
Can you please add a Koan for the Java 8 features like Lambdas and Streams

**Comment by darsen** [comment]
@mavrukin , check out my fork: https://github.com/darsen/java-koans.
I have created some java7 and java8 koans.
@matyb I would like to send you a pull request, would you like to take a look before I do it?

**Comment by mavrukin** [comment]
I like it, I think the stream stuff look really good.  I'd add a bit more
stuff on the lambda side, otherwise, looks pretty good.

Michael

**Comment by matyb** [comment]
Super slick, that's a good amount of cohesive content. Will test with a couple runtimes and OS's tonight and pull.

**Comment by dcmoore** [comment]
Looking forward to this getting pulled in as I'd like to build upon the changes that were made here.

**Comment by matyb** [comment]
Ya absolutely, darsen wanna send a pull request? I'd happily merge in

**Comment by matyb** [comment]
Codes up, let me know if u see any issues. Thanks for PR darsen.
