### ISSUE TITLE
demonstrate lambda sans multithreading or sleeping

### ISSUE THREAD

**Issue by matyb** [matyb/java-koans#45]
AboutLambdas.simpleLambda doesnt need to use a thread nor sleep to prove its point. Using lambdas in a new thread could be its own lesson. As it stands it could mislead users into thinking its necessary to spawn a thread.

**Comment by dklotz** [comment]
The current version of AboutLambdas does not use threads, so this issue can probably be closed, right @matyb ?

**Comment by matyb** [comment]
Yeah I think you're right, good :eye: @dklotz
