### ISSUE TITLE
Source path must actually exist in AboutTryWithResources

### ISSUE THREAD

**Issue by ljocampo** [matyb/java-koans#49]
I'm getting the following exception when running java7.AboutTryWithResources

Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Source path must actually exist. (/Users/luis/dev/java-koans/koans/src/java7/WorkException)

I've moved both WorkException and CloseException out of the class, And I get Symbol cannot be found.

Please can anyone tell what I'm doing wrong, How can I address this issue so I can move on with the koans

**Comment by matyb** [comment]
Great question, not sure its anything you're doing. Will you reply with: 
-the output of running "java -version" from the command line?
-what OS you are using?
-your copy of AboutTryWithResources

You'll be back up and running soon.

**Comment by matyb** [comment]
Nevermind, I am able to recreate. Will have fix together soon I think.

**Comment by matyb** [comment]
darsen - did u figure out how to fix this? I added "sourceFile.exists()" to DynamicClassLoader :87 and that appeared to do the trick, but I didn't see it in your branch, wondering if you found a smarter alternative?

**Comment by matyb** [comment]
ljocampo if you comment out or remove the AboutTryWithResources suite in the file /Users/luis/dev/java-koans/koans/app/config/PathToEnlightenment.xml you should be able to continue while we work this out. If that doesn't do it, retain that change, but also run './run.sh clean' to clear that busted class out.

**Comment by ljocampo** [comment]
@matyb Thank you for the quick reply I'll do that. Awesome work you've done.

**Comment by ljocampo** [comment]
@matyb FYI had to comment out AboutDefaultMethods in PathToEnlightenment.xml also, now I'm able to move on with AboutOptional, and thank you in advanced.

**Comment by matyb** [comment]
ljocampo no problem, glad you're not stalled any longer. I think I have a fix but want to test it before lobbing it up here. Thanks for taking the time to report this.

**Comment by ljocampo** [comment]
@matyb Great! Thank you for all the time and work invested on this issue.

**Comment by darsen** [comment]
I am getting "java.io.FileNotFoundException: I do not exist! (The system cannot find the file specified)" in AboutTryWithResources. But that's because the catch statement is missing.

However, no problems with  WorkException and CloseException.

**Comment by darsen** [comment]
OK I can see it now...

**Comment by darsen** [comment]
OK, so I moved these classes to inner and now it should work; pull request issued.
Thank you @ljocampo and @matyb .

**Comment by ljocampo** [comment]
Made the changes on my AboutTryWithResources and is working smoothly, Now after completing the koans on it I get the same exception "Source path must actually exist" for StringUtils in AboutDefaultMethods, any ideas on this one since the interface is define at the top?

**Comment by ljocampo** [comment]
Never mind moved the interface to inner and is working ok.

**Comment by matyb** [comment]
Awesome great work @ljocampo and @darsen thanks for all the help. Moved StringUtils inside AboutDefaultMethods as well. Let me know if you spot any other issues and I'll patch those up too.

**Comment by ljocampo** [comment]
Moved the interface to inner in AboutLambdas. Koans 239/239

**Comment by matyb** [comment]
K I'm reopening until I get that fixed, good catches!

**Comment by matyb** [comment]
Just updated the last few files @ljocampo. Thanks again man.
