### ISSUE TITLE
AboutPrimitives 

### ISSUE THREAD

**Issue by huyansheng3** [matyb/java-koans#53]
## 1.the compile error infomation 
> Compile Output:
D:\2015_the_last_semester\java-koans-master\koans\src\beginner\AboutPrimitives.j
ava:48: 错误: 过大的整数: -9223372036854775808
                assertEquals(Long.MIN_VALUE,-9223372036854775808);
                                             ^
    1 个错误

> Compiling "D:\2015_the_last_semester\java-koans-master\koans\src\beginner\AboutP
rimitives.java" failed.
The exit status was: 1
*****************************************************************

## 2.the code i write down
```
	@Koan
	public void longsHaveALargerRangeThanInts() {
		assertEquals(Long.MIN_VALUE,-9223372036854775808);
		assertEquals(Long.MAX_VALUE,9223372036854775807);
	}
```

when i save the code ,the complie tell me that the Number is too large!

but i write another code to test it,the MAX_VALUE and MIN_VALUE is right,please tell me what happen? by the way,is there any way to skip some question?

```
public class NumberTest{
	public static void main(String[] args) {
		System.out.println("Long.MIN_VALUE : "+Long.MIN_VALUE);
		System.out.println("lONG.MAX_VALUE : "+Long.MAX_VALUE);
                // it print out Long.MIN_VALUE : -9223372036854775808
                //                  Long.MAX_VALUE : 9223372036854775807
	}
}
```

**Comment by huyansheng3** [comment]
ok, i lose the "L" at the end of number when i use the long!

**Comment by matyb** [comment]
Right, the L tells the compiler to interpret value as a long which can hold values that large. Without it, it's seen as an integer which cannot hold values that large.

To skip a koan, you can comment out the assert in it. Providing that as a feature is a cool idea.
