### ISSUE TITLE
Run koans in "non-interactive" mode

### ISSUE THREAD

**Issue by DavidWhitlock** [matyb/java-koans#57]
Hey, @matyb and friends.  As you may recall, I use the Java Koans in my Advanced Java Programming course at Portland State University.  The students find the koans to be very valuable and I feel they provide an appropriately broad introduction to the Java language and its core APIs.

My students work on the koans during the first couple of weeks of classes and then they submit them to me for grading.  Currently, I have a script that runs the koans for a student, sleeps while koans compile and run, send the letter 'Q' to standard input, captures the output into a file, and then moves on to the next student.

The school's machine that I run the koans on can be under heavy load at times and I've had to adjust the script to sleep for 4 minutes in order to ensure that all of the koans are compiled before sending the 'Q' to exit.  When I've got more than 30 student submissions to grade, this process can take a long time.

Last summer, my grader suggested that I add a "run in non-interactive mode" to the koans framework that would wait for all of the koans to compile and report their results before simply exiting.  It wouldn't need to prompt for the user to enter 'Q' in standard in.

I'm not sure if the koans framework can easily handle this use case, so I wanted to ask you guys about its feasibility before diving into it too deeply.

So, what do you think?  Would running the koans in a non-interactive mode be feasible?  If so, do you have any recommendations about how I might approach adding a non-interactive mode?

Thanks,

Dave

**Comment by matyb** [comment]
yeah it totally can, in fact - that's how it used to work back when i started it. i doubt this is that difficult, i'll leave this open and see if i can get it implemented easily. i really don't think it'd take too much, just need to pull out of my memory the best place to implement that.

**Comment by DavidWhitlock** [comment]
Great.  Let me know if there is anything I can do to help develop or test this functionality.

**Comment by matyb** [comment]
@DavidWhitlock sorry about the delay, life's been hectic to put it mildly. Here's what I'm thinking tell me if this works for you.

The build is currently in ant (probably another issue I should log :)), I'm thinking adding a target to:

1. compile all the koans
2. update all the file "hashes" to indicate no compilation is necessary
3. set system property to disable the "press Q" behavior
4. run the koans w/ the existing runner

This will just indicate to your grading suite/script success/failure like it does today, not necessarily which koan failed (though that'll be written to stdout).

Right now the time consuming part is compiling every single koan class incrementally. This definitely speeds up interactive koans, but if you just want to "let it rip" there's a ton of overhead associated w/ each compile phase that when summed together yields an awful lot of waste. If you think knowing which koan failed (ie a return code 1 for first koan failed, 2 for 2nd, etc. and 0 for all succeed) I can alter step 4. 

I'll count on running with this, but let me know if you can think of something w/ more reuse and efficiency or that would work better.

**Comment by DavidWhitlock** [comment]
Hey, @matyb.  Thanks for getting back to me.

That sounds like a fine plan.  Running with a system property will work for me and I don't mind a slower compile process as long as the JVM exits at the end.  Printing out which koans failed is fine with me.  I don't need the JVM's exit code to reflect the number of failures.  A non-zero exit code would be cool if any test failed, but it's not necessary.

Thanks again!

Dave

**Comment by matyb** [comment]
@DavidWhitlock added an "interactive" mode to koans/app/config/config.properties, feel free to flip that to false to enable the behavior you seek.

Hope this helps. Let me know if you find to problems.

**Comment by DavidWhitlock** [comment]
Thanks, @matyb.  I'll check it out this weekend.

**Comment by DavidWhitlock** [comment]
The changes look good, @matyb.  They will help my automated grading process a lot.  Thanks again!

**Comment by matyb** [comment]
Great to hear @DavidWhitlock, thanks for following up
