### ISSUE TITLE
Run koan on IntelliJ IDEA

### ISSUE THREAD

**Issue by profesorasix** [matyb/java-koans#60]
Hello, 
Can anyone provide a quick guide about how to run java-koan file-separately (like your [video](https://www.youtube.com/watch?time_continue=8&v=yG6ct5j0Rms))

Thanks in advanced.

**Comment by matyb** [comment]
Ya, "./run.sh beginner.AboutKoans" will run koans/src/beginner/AboutKoans.java

Works with run.bat as well

**Comment by matyb** [comment]
If it's in your ide, you can run main method w first program argument as beginner.AboutKoans
