### ISSUE TITLE
Should Koan output "give away" the solution?

### ISSUE THREAD

**Issue by DavidWhitlock** [matyb/java-koans#73]
Hey, @matyb and friends.

One of my students was surprised by the fact that the output of the koans runner essentially "gives away" the answer for many of the koans.

![image](https://user-images.githubusercontent.com/2935912/27762384-ed457496-5e25-11e7-9637-71e80a45fca8.png)

> The part where it says 
> "What went wrong:
> expected:<2> but was:<REPLACE ME>"
>
> This part basically gives you the answers. Not sure if it's intended or not but it always appears before even giving my first attempt at the problem.

It got me thinking: I know the intent of the Koans is to encourage the student to think about the solution.  A motivated and intentional student will do so.  However, anyone just trying to "get through the koans" will be tempted to just replace the `__` with the answer provided and move on to the next one.

Would it be appropriate for the koan runner to issue a different message when the actual value is `__` (`REPLACE ME`) that doesn't immediately reveal the solution?  Of course, a student could enter e bogus value instead of `__` to reveal the answer, but that requires a little more thinking than just copying what's there in the runner output.

**Comment by matyb** [comment]
Oh yeah, I had a feeling this would come up eventually :smile: 

IMO a user looking to turn their brain off and 'get credit' for doing something will always find a way to do just that. Making the solution harder to find may yield better engagement w/ users that fit that pattern, but it would be at the expense of self styled learners that will see an answer and before moving on - contemplate how to arrive at that answer. These were really only ever intended for people with a genuine interest in the language looking for a high level overview of its features and some experience tinkering with those features.

One suitable compromise, and it's something I'd certainly concede I didn't think through as carefully as I perhaps should have; would be the depth to the layers of abstraction used in any given lesson. For instances like those in the beginner package where it's preferable for the user to have to think through as little as possible at each turn; the copy from the failure and paste into the koan kind of solution is perfect. For the more difficult packages where it's fair to expect a user to know more, adding more abstraction between the __ and the assertion(s) can help to eliminate the urge to copy and paste... though someone looking to game the system can always short circuit all of that abstraction and/or delete the assertions altogether and get a passing score. 

If you or your students find ways to better suit the difficulty of a koan to it's intended subject matter, definitely fire some PR's my way and I'll be happy to merge them, that'd be a great way to make this better for everyone; but it's also one of those things outside input would be most helpful for. I've fallen out of touch with the average java developer lately :stuck_out_tongue:

**Comment by matyb** [comment]
@DavidWhitlock 
What the user saw was the default error message, but that message can be overridden by supplying a key of the [package.class.method in the internationalization file](https://github.com/matyb/java-koans/blob/master/koans/app/config/i18n/messages_en.properties#L1).

I haven't coded actual lessons for each one, just the first few.

**Comment by DavidWhitlock** [comment]
👍 

That sounds reasonable.  I'll ponder this some more and talk with more of my students about their experiences with the koans.  As you point out, I can always send a pull request with changes that I think will address this issue.

Thanks!
