### ISSUE TITLE
assertNotSameInstance a bit unclear

### ISSUE THREAD

**Issue by eliot1785** [matyb/java-koans#79]
Thanks for creating these koans. 

I think the goal/instructions for assertNotSameInstance is a bit unclear. It's the same code as the previous one, just with assertNot instead of assert. I can just delete the "Not" but that feels like the wrong way. Still, I'm guessing that's how it's suggested to proceed.

**Comment by matyb** [comment]
good point. im curious though, is there an improvement to how to articulate that lesson? assertNot methods are a cop out 99% of the time IMO, unless it's used to verify serialization/cloning behaviors those asserts are likely being misused. maybe it should be removed?

what do u think, remove the koan, or is there a clearer way to communicate such a clumsy concept?

**Comment by kjc** [comment]
Ack!  I didn't realize every --ammend in my own repo would show up here as a new comment.  Sorry about all the spam.

**Comment by eliot1785** [comment]
I just saw the update, looks good. Thanks!
