### ISSUE TITLE
nestedIfsWithoutCurlysAreReallyMisleading doesn't live up to the name

### ISSUE THREAD

**Issue by eliot1785** [matyb/java-koans#84]
nestedIfsWithoutCurlysAreReallyMisleading doesn't actually contain "nested ifs without curlys." All the ifs/elses have curly brackets. Maybe you did a code cleanup and accidentally fixed this?

From an old issue you can see how it used to be: https://github.com/matyb/java-koans/issues/16

**Comment by kjc** [comment]
It looks like commit aadbd55 (in PR #59) [combined two koans](https://github.com/matyb/java-koans/commit/aadbd555ec982fcf7980efcf7b9de5297a9fa468#diff-c4b0526165cc6a76155492c6b5e779e8L48) --- `nestedIfsWithoutCurlysAreReallyMisleading` and `ifAsIntended` --- resulting in a mix of the two.
