### ISSUE TITLE
error in instructions for toStringIsTestedForNullWhenInvokedImplicitly

### ISSUE THREAD

**Issue by eliot1785** [matyb/java-koans#85]
In the instructions for toStringIsTestedForNullWhenInvokedImplicitly it says "String concatenation implicitly invokes toString on Objects, unless they are null"

However, I believe it will just use the string "null" in this case. Maybe it was different in an older version of Java?

Also I'm not sure what the code itself was supposed to demonstrate, since none of those values are null.

**Comment by matyb** [comment]
good catch. the method name and contents didnt jive.
