### ISSUE TITLE
AboutFileIO Koan basicFileWritingAndReading() line 29

### ISSUE THREAD

**Issue by Danc2050** [matyb/java-koans#96]
There is (garbage?) output that is inside the expected string on line 45. This  makes comparing the string difficult unless one passes in the identical String constructor `new String(in))` into the assert or uses the trim function.
![expected](https://user-images.githubusercontent.com/32185616/61737081-58256700-ad3c-11e9-87d0-49ce97b2d17e.png)

**Comment by matyb** [comment]
yeah that doesn't make sense... that char[50] instead of char[stringValue.length()] is adding unintended characters. tell me if #97 doesn't make more sense.

**Comment by Danc2050** [comment]
Looks good to me!
